### ISSUE TITLE
With all due respect, this is a poor lesson.

### ISSUE THREAD

**Issue by Ary770** [learn-co-curriculum/js-ajax-intro-to-ajax-readme#3]
I felt many concepts and lines of code were left unexplained. Not even a reference as to where to get a basic understanding of them. I hope I'll be able to solve the labs...

**Comment by maxwellbenton** [comment]
Hi @Ary770,

Thank you for providing feedback.

We are in the process of updating this section, will be restructuring existing content and adding additional lessons. This issue is recorded and will be resolved in the next version of learn.co's full stack web development track

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.
