### ISSUE TITLE
Mentioning what APIs and JSON is? (Poorly Written Lesson)

### ISSUE THREAD

**Issue by AkaKuro4Ever** [learn-co-curriculum/js-ajax-intro-to-ajax-readme#6]
It seems weird to be talking about and using JSON built in methods when we have never mentioned it before this time. We also never fully explained things like what an API entails or how JSON and XML are different (and if XMLHTML is the same or different from that.) Just a bit confusing and the lesson moves really fast.

**Comment by AkaKuro4Ever** [comment]
I also don't understand why 
```
function showRepositories(event, data) {
  //this is set to the XMLHttpRequest object that fired the event
  var repos = JSON.parse(this.responseText)
  console.log(repos)
  console.log(repos[0])
  const repoList = `<ul>${repos.map(r => '<li>' + r.name + ' - <a href="#" data-repo="' + r.name + '" onclick="getCommits(this)">Get Commits</a></li>').join('')}</ul>`

  document.getElementById("repositories").innerHTML = repoList
}
```

even has 2 arguments when they are never mentioned or even used in the final method. Please expand this lesson. It was very poorly explained.

**Comment by maxwellbenton** [comment]
Hi @Ary770,

Thank you for providing feedback.

We are in the process of updating this section, will be restructuring existing content and adding additional lessons. This issue is recorded and will be resolved in the next version of learn.co's full stack web development track

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.
